trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.0'

- task: TerraformTaskV4@1
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceArm: '<your-service-connection>'
    ensureBackend: true

- task: TerraformTaskV4@1
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: '<your-service-connection>'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: TerraformTaskV4@1
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: '<your-service-connection>'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    args: '-auto-approve'
